# ecr-login/action.yml
name: 'ecr-login'
description: 'Log in to Amazon ECR using AWS GitHub Action role'

inputs:
  aws-region:
    description: 'aws-region'
    default: 'ap-northeast-2'

outputs:
  registry:
    description: "The URI of the ECR Private or ECR Public registry."
    value: ${{ env.ECR_REGISTRY }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.aws-gh-action-role }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: set output
      id: set-registry-output
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: echo "ECR_REGISTRY=${{ env.ECR_REGISTRY }}" >> $GITHUB_ENV
      shell: bash

    - name: always_fail
      id: always_fail
      run: false
      shell: bash

    #(admin) to-do : change if statement
    - name: post github actions - save state
      id: save_state
      run: |
        WORKFLOW_JOB_NAME="${{ inputs.workflow-job-name }}"
        WORKFLOW_JOB_STATUS="success"
        if [[ "${{ steps.configure-aws-credentials.outcome }}" == "failure" || "${{ steps.login-ecr.outcome }}" == "failure" || "${{ steps.set-registry-output.outcome }}" == "failure" || "${{ steps.always_fail.outcome }}" == "failure" ]]; then
          WORKFLOW_JOB_STATUS="failure"
        fi
        echo "::set-output name=workflow_job_name::$WORKFLOW_JOB_NAME"
        echo "::set-output name=workflow_job_status::$WORKFLOW_JOB_STATUS"
      shell: bash
      if: ${{ always() }}

    - name: post github actions
      uses: Hyunju-Sung/actions-post-deploy-hj@0.0.4
      with:
        workflow-job-name: ${{ steps.save_state.outputs.workflow_job_name }}
        workflow-job-status: ${{ steps.save_state.outputs.workflow_job_status }}
        trigger-delete-git-tag: true
        tag: 1.2.3.4
      if: ${{ always() }} && ${{ steps.save_state.outputs.workflow_job_status }} == "failure"