# ecr-login/action.yml
name: 'ecr-login'
description: 'Log in to Amazon ECR using AWS GitHub Action role'

inputs:
  aws-gh-action-role:
    description: "AWS GitHub Action role ARN"
    required: true
  aws-region:
    description: 'aws-region'
    default: 'ap-northeast-2'
  workflow-job-name:
    description: "workflow job name calling"
    required: true
  slack_webhook_url:
    description: "workflow job name calling"
    required: true
outputs:
  registry:
    description: "The URI of the ECR Private or ECR Public registry."
    value: ${{ env.ECR_REGISTRY }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws-gh-action-role }}
        aws-region: 'ap-northeast-7'

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: set output
      id: set-registry-output
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: echo "ECR_REGISTRY=${{ env.ECR_REGISTRY }}" >> $GITHUB_ENV
      shell: bash

    #(admin) to-do
    - name: post github actions - save state
      run: |
        WORKFLOW_JOB_NAME="${{ inputs.workflow-job-name }}"
        WORKFLOW_JOB_STATUS="success"
        if [ ${{ steps.configure-aws-credentials.outcome }} == "failure" || ${{ steps.login-ecr.outcome }} == "failure" || ${{ steps.set-registry-output.outcome }} == "failure"]; then
          WORKFLOW_JOB_STATUS="failure"
        fi
        echo "WORKFLOW_JOB_NAME=$WORKFLOW_JOB_NAME" >> $GITHUB_ENV
        echo "WORKFLOW_JOB_STATUS=$WORKFLOW_JOB_STATUS" >> $GITHUB_ENV
      shell: bash

    - name: post github actions
      uses: Hyunju-Sung/actions-post-deploy-hj@0.0.4
      with:
        workflow-job-name: $WORKFLOW_JOB_NAME
        workflow-job-status: $WORKFLOW_JOB_STATUS
        slack_webhook_url: ${{ inputs.SLACK_WEBHOOK_URL }}
      if: ${{ failure() }}