name: 'ecr-login'
description: 'ecr-login'

inputs:
  aws-gh-action-role:
    description: "AWS github action role arn"
    required: true
  outputs:
    registry:
      description: "The URI of the ECR Private or ECR Public registry."
      value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: 'composite'
  steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws-gh-action-role }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
